### PR TITLE
allow custom git commithash commands"

### PR DESCRIPTION
**Pull request by robertleib**

### CODE REVIEW

**Comment by robertleib** [comment]
We ended up needing:
```
const gitRevisionPlugin = new GitRevisionPlugin({commithashCommand: 'rev-list --max-count=1 --no-merges HEAD'});
```
because we have some CI merges that end up as the last commit.

**Comment by robertleib** [comment]
@pirelenito is there anything I can do to help get this PR approved?  Thanks!

**Comment by pirelenito** [comment]
Hi @robertleib, really sorry for not replying to you earlier.

I want to give it a thought about the exact public API. I promise a reply this weekend.

Thanks again for contributing!

**Comment by pirelenito** [comment]
Hi, I'll merge your PR, add tests docs and will generate a new version soon.

**Comment by pirelenito** [comment]
Just published `2.4.0` with the change:

https://github.com/pirelenito/git-revision-webpack-plugin#commithashcommand-rev-parse-head

Thanks again for contributing! And sorry for taking so long to reply.

**Comment by robertleib** [comment]
Great, thanks!

**Pull request merged**
