### PR TITLE
Fix issue with filename functions

### LINKED ISSUE #39: output.filename as function doesn't work
With latest webpack (4.26.1) using options.filename with a function throws error when adding GitRevisionPlugin to plugins array

```javascript
return {
        entry: {
            app: `./${SRCFOLDER}/entrypoints/main.js`
        },
        output: {
            filename: () => 'test.js' 
            // with example function from docs same error
            filename: (chunkData) => {
                 return chunkData.chunk.name === 'main' ? '[name].js': '[name]/[name].js';
           },
        },
 ...

        plugins: [
            new GitRevisionPlugin({
                versionCommand: 'describe --always --tags --abbrev=0'
            }),
```
Console output:
```
ERROR in chunk app [entry]
() => 'test.js'
path.replace is not a function
error Command failed with exit code 2.
```

**Other relevant information:**
webpack version:  4.26.1
Node.js version: 8.11.2
Operating System: windows 10
Additional tools:

### PR DESCRIPTION
**Pull request by njbmartin**
Fixes #39

Not sure which plugin has caused the issue but this resolves the compatibility.

### CODE REVIEW

**Comment by ViktorAksionov** [comment]
Any plans to merge it?

**Comment by swarthy** [comment]
Related webpack-contrib/mini-css-extract-plugin/issues/417

**Comment by pmeinhardt** [comment]
I'm getting the same error after upgrading webpack and webpack-related packages in a project.
Would love to see it fixed, so I can continue using this great plugin @pirelenito 💚

**Comment by pirelenito** [comment]
Hi,

Thank you all for understanding this long delay on getting back to you. I'll merge this and get a patch released ASAP.

@njbmartin do you think it would be possible to do a followup PR with a test covering this issue?

Cheers! ❤️

**Comment by pirelenito** [comment]
Just released `3.0.4` with your fix included. ✋

**Pull request merged**
